# FOSSA Configuration for opnDossier
# Pipeline v2 Compliance: License Scanning and Policy Enforcement

version: 3

project:
  id: github.com/EvilBit-Labs/opnDossier
  name: opnDossier
  policy: default
  link: https://github.com/EvilBit-Labs/opnDossier

targets:
  only:
    - type: go
      path: .

analyze:
  modules:
    - name: go
      type: go
      target: .
      path: .

experimental:
  gradle:
    configurations-only: []
    only-configuration-deps: false
