# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"

run:
  concurrency: 8
  timeout: 30m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: false

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - canonicalheader
    - containedctx
    - copyloopvar
    - cyclop
    - decorder
    - dupl
    - durationcheck
    - embeddedstructfieldcheck
    - errchkjson
    - errcheck
    - errname
    - errorlint
    # - exhaustive - disabled: we'll come back to this
    # - exhaustruct - disabled: we'll come back to this
    - exptostd
    - ginkgolinter
    - fatcontext
    - funcorder
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gomoddirectives
    - goprintffuncname
    - gosec
    - govet
    - iface
    - inamedparam
    - ineffassign
    - intrange
    - loggercheck
    - makezero
    - mirror
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    # - prealloc # Disabled: this can be premature optimization
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    #- tagliatelle # Disabled: currently this is more trouble than it's worth
    - testableexamples
    - thelper
    - testifylint
    - testpackage
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - std-error-handling
  disable:
    - gomodguard
  #  - wrapcheck # Disabled: most violations are internal package calls within same module
  settings:
    cyclop:
      max-complexity: 30
      package-average: 10.0
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - hugeParam
        - rangeExprCopy
        - rangeValCopy
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false

    embeddedstructfieldcheck:
      forbid-mutex: true
    tagliatelle:
      case:
        overrides:
          - pkg: internal/model/opnsense.go
            ignore: true

    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)
    exhaustive:
      check:
        - switch
        - map
    exhaustruct:
      exclude:
        - ^net/http.Client$
        - ^net/http.Cookie$
        - ^net/http.Request$
        - ^net/http.Response$
        - ^net/http.Server$
        - ^net/http.Transport$
        - ^net/url.URL$
        - ^os/exec.Cmd$
        - ^reflect.StructField$
        - ^github.com/Shopify/sarama.Config$
        - ^github.com/Shopify/sarama.ProducerMessage$
        - ^github.com/mitchellh/mapstructure.DecoderConfig$
        - ^github.com/prometheus/client_golang/.+Opts$
        - ^github.com/spf13/cobra.Command$
        - ^github.com/spf13/cobra.CompletionOptions$
        - ^github.com/stretchr/testify/mock.Mock$
        - ^github.com/testcontainers/testcontainers-go.+Request$
        - ^github.com/testcontainers/testcontainers-go.FromDockerfile$
        - ^golang.org/x/tools/go/analysis.Analyzer$
        - ^google.golang.org/protobuf/.+Options$
        - ^gopkg.in/yaml.v3.Node$
    funcorder:
      struct-method: false
    funlen:
      lines: 100
      statements: 50
    gochecksumtype:
      default-signifies-exhaustive: false
    gocognit:
      min-complexity: 20

    govet:
      enable-all: true
      disable:
        - fieldalignment # Disabled: this is a known issue with the govet tool
      settings:
        shadow:
          strict: true
    inamedparam:
      skip-single-param: true

    mnd:
      ignored-functions:
        - args.Error
        - flag.Arg
        - flag.Duration.*
        - flag.Float.*
        - flag.Int.*
        - flag.Uint.*
        - os.Chmod
        - os.Mkdir.*
        - os.OpenFile
        - os.WriteFile
        - prometheus.ExponentialBuckets.*
        - prometheus.LinearBuckets

    nakedret:
      max-func-lines: 1
    nolintlint:
      allow-no-explanation: [ funlen, gocognit, golines ]
      require-explanation: true
      require-specific: true
    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx
    sloglint:
      no-global: all
      context: scope
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1016
        - -QF1008
    usetesting:
      os-temp-dir: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  uniq-by-line: true
  fix: true
formatters:
  enable:
    - golines
    - gofumpt
    - goimports
    - gci
  settings:
    gofumpt:
      module-path: "github.com/unclesp1d3r/opnFocus"
      extra-rules: true
    golines:
      max-len: 120
  exclusions:
    generated: lax
