merge_protections:
  - name: Enforce conventional commit
    description: Make sure that we follow https://www.conventionalcommits.org/en/v1.0.0/
    if:
      - base = main
    success_conditions:
      - "title ~= ^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:\\(.+\\))?:"
  - name: Do not merge outdated PRs
    description: Make sure PRs are within 3 commits before merging
    if:
      - base = main
    success_conditions:
      - "#commits-behind <= 3"
  - name: Require CI checks are successful
    if:
      - base = main
    success_conditions:
      - check-success ~= (?i)^(CI / )?build$
      - check-success ~= (?i)^(CI / )?integration-tests$
      - check-success ~= (?i)^(CI / )?test$
      - check-success ~= (?i)^(CI / )?lint$
