package formatters

import (
	"bytes"
	"fmt"
	"io"

	"github.com/EvilBit-Labs/opnDossier/internal/diff"
	"github.com/EvilBit-Labs/opnDossier/internal/markdown"
)

// htmlShell wraps rendered HTML body content in a self-contained HTML document
// with embedded CSS for offline viewing.
const htmlShell = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Configuration Diff Report</title>
<style>
:root {
  --bg: #fff; --text: #1a1a2e; --border: #e0e0e0;
  --added: #28a745; --removed: #dc3545; --modified: #fd7e14;
  --high: #dc3545; --medium: #fd7e14; --low: #28a745;
  --bg-surface: #f8f9fa; --code-bg: #f4f4f4;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #1a1a2e; --text: #e0e0e0; --border: #333;
    --bg-surface: #16213e; --code-bg: #1e1e2e;
  }
}
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  max-width: 960px; margin: 2rem auto; padding: 0 1rem;
  background: var(--bg); color: var(--text); line-height: 1.6; }
h1, h2, h3 { border-bottom: 1px solid var(--border); padding-bottom: 0.3em; }
table { border-collapse: collapse; width: 100%%; margin: 1em 0; }
th, td { border: 1px solid var(--border); padding: 0.5em 0.75em; text-align: left; }
th { background: var(--bg-surface); font-weight: 600; }
code { background: var(--code-bg); padding: 0.15em 0.3em; border-radius: 3px; font-size: 0.9em; }
details { margin: 0.5em 0; }
summary { cursor: pointer; font-weight: 600; }
@media print { body { max-width: 100%%; margin: 0; } }
</style>
</head>
<body>
%s
<footer style="margin-top:2rem; padding-top:1rem; border-top:1px solid var(--border); font-size:0.85em; color:#888;">
Generated by opnDossier
</footer>
</body>
</html>
`

// HTMLFormatter formats diff results as a self-contained HTML report
// by rendering markdown through goldmark.
type HTMLFormatter struct {
	writer io.Writer
}

// NewHTMLFormatter creates a new HTML formatter.
func NewHTMLFormatter(writer io.Writer) *HTMLFormatter {
	return &HTMLFormatter{
		writer: writer,
	}
}

// Format generates markdown via MarkdownFormatter, converts it to HTML
// via goldmark, and wraps it in a self-contained HTML document.
func (f *HTMLFormatter) Format(result *diff.Result) error {
	// Generate markdown
	var mdBuf bytes.Buffer
	mdFormatter := NewMarkdownFormatter(&mdBuf)
	if err := mdFormatter.Format(result); err != nil {
		return fmt.Errorf("failed to generate markdown for HTML conversion: %w", err)
	}

	// Convert markdown to HTML body via goldmark
	htmlBody, err := markdown.RenderMarkdown(mdBuf.String())
	if err != nil {
		return fmt.Errorf("failed to convert markdown to HTML: %w", err)
	}

	// Wrap in self-contained HTML shell
	_, err = fmt.Fprintf(f.writer, htmlShell, htmlBody)
	return err
}
