package converter

import (
	"fmt"
	"strings"

	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
	goldmark_parser "github.com/yuin/goldmark/parser"
	"github.com/yuin/goldmark/renderer/html"
)

// htmlShell wraps rendered HTML body content in a self-contained HTML document
// with embedded CSS for offline viewing. No external resources are loaded.
const htmlShell = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>OPNsense Configuration Report</title>
<style>
:root {
  --bg: #fff; --text: #1a1a2e; --border: #e0e0e0;
  --bg-surface: #f8f9fa; --code-bg: #f4f4f4;
  --note: #0969da; --warning: #9a6700; --tip: #1a7f37;
  --caution: #cf222e; --important: #8250df;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #1a1a2e; --text: #e0e0e0; --border: #333;
    --bg-surface: #16213e; --code-bg: #1e1e2e;
    --note: #58a6ff; --warning: #d29922; --tip: #3fb950;
    --caution: #f85149; --important: #bc8cff;
  }
}
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  max-width: 960px; margin: 2rem auto; padding: 0 1rem;
  background: var(--bg); color: var(--text); line-height: 1.6; }
h1, h2, h3 { border-bottom: 1px solid var(--border); padding-bottom: 0.3em; }
h4, h5, h6 { margin-top: 1.5em; }
table { border-collapse: collapse; width: 100%%; margin: 1em 0; }
th, td { border: 1px solid var(--border); padding: 0.5em 0.75em; text-align: left; }
th { background: var(--bg-surface); font-weight: 600; }
code { background: var(--code-bg); padding: 0.15em 0.3em; border-radius: 3px; font-size: 0.9em; }
pre { background: var(--code-bg); padding: 1em; border-radius: 6px; overflow-x: auto; }
pre code { background: none; padding: 0; }
details { margin: 0.5em 0; }
summary { cursor: pointer; font-weight: 600; }
ul, ol { padding-left: 1.5em; }
li { margin: 0.25em 0; }
blockquote { border-left: 4px solid var(--border); margin: 1em 0; padding: 0.5em 1em;
  background: var(--bg-surface); }
@media print { body { max-width: 100%%; margin: 0; } }
</style>
</head>
<body>
%s
<footer style="margin-top:2rem; padding-top:1rem; border-top:1px solid var(--border); font-size:0.85em; color:#888;">
Generated by opnDossier
</footer>
</body>
</html>
`

// goldmarkRenderer is a pre-configured goldmark instance for converting markdown to HTML.
// It matches the configuration in internal/markdown/formatters.go:RenderMarkdown().
var goldmarkRenderer = goldmark.New(
	goldmark.WithExtensions(extension.Table),
	goldmark.WithParserOptions(
		goldmark_parser.WithAutoHeadingID(),
	),
	goldmark.WithRendererOptions(
		html.WithHardWraps(),
		html.WithXHTML(),
		html.WithUnsafe(),
	),
)

// renderMarkdownToHTML converts markdown content to a self-contained HTML document.
// It uses goldmark for markdown-to-HTML conversion and wraps the result in htmlShell.
func renderMarkdownToHTML(md string) (string, error) {
	var buf strings.Builder
	if err := goldmarkRenderer.Convert([]byte(md), &buf); err != nil {
		return "", fmt.Errorf("failed to convert markdown to HTML: %w", err)
	}

	return fmt.Sprintf(htmlShell, buf.String()), nil
}
