package cmd

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestDocsCmdGeneratesHeadlineCommandPages exercises runGenerateMarkdownDocs
// against a throwaway output directory and asserts that each headline command
// produced a non-empty markdown page containing its Cobra Short/Example text.
// This keeps the CLI reference tied to the real command tree so a regression
// (a removed command, an emptied Long, a stripped Example) fails CI.
func TestDocsCmdGeneratesHeadlineCommandPages(t *testing.T) {
	// Do NOT use t.Parallel() — cmd package uses package-level flag globals.
	// See GOTCHAS §1.1.
	outputDir := t.TempDir()

	// runGenerateMarkdownDocs calls cmd.Root() internally, so any registered
	// command resolves to rootCmd. Pass docsCmd directly.
	var stdout bytes.Buffer
	docsCmd.SetOut(&stdout)
	t.Cleanup(func() { docsCmd.SetOut(nil) })

	require.NoError(t, runGenerateMarkdownDocs(docsCmd, []string{outputDir}))

	// Every headline command must produce a markdown file under outputDir.
	for _, name := range []string{
		"opnDossier.md",
		"opnDossier_audit.md",
		"opnDossier_convert.md",
		"opnDossier_display.md",
		"opnDossier_diff.md",
		"opnDossier_sanitize.md",
		"opnDossier_validate.md",
	} {
		path := filepath.Join(outputDir, name)
		stat, err := os.Stat(path)
		require.NoErrorf(t, err, "expected generated page %s", name)
		assert.Positivef(t, stat.Size(), "page %s should be non-empty", name)
	}

	// Spot-check that the audit page contains content lifted from Cobra metadata.
	auditPath := filepath.Join(outputDir, "opnDossier_audit.md")
	body, err := os.ReadFile(auditPath)
	require.NoError(t, err)
	auditBody := string(body)
	assert.Contains(t, auditBody, "Run security audit and compliance checks",
		"generated audit page should include the Cobra Short text")
	assert.Contains(t, auditBody, "opnDossier audit config.xml",
		"generated audit page should include Example invocations")

	// Front-matter structural assertion — MkDocs strict mode fails if the
	// delimiters or required keys drift.
	assert.True(t, strings.HasPrefix(auditBody, "---\n"),
		"page must start with front-matter delimiter")
	assert.Contains(t, auditBody, "\ntitle: opnDossier audit\n",
		"front-matter must include title derived from filename")
	assert.Contains(t, auditBody, "\ngenerated: true\n",
		"front-matter must include generated: true")
	assert.Contains(t, auditBody, "Auto-generated by 'opnDossier docs'",
		"generated pages should carry the authoring banner")

	// linkHandler preservation — cross-link targets retain the "opnDossier_"
	// prefix so they resolve against the files on disk. If someone "helpfully"
	// strips the prefix, every internal link on the MkDocs site 404s.
	rootPath := filepath.Join(outputDir, "opnDossier.md")
	rootBody, err := os.ReadFile(rootPath)
	require.NoError(t, err)
	assert.Contains(t, string(rootBody), "](opnDossier_audit.md)",
		"root page must retain prefixed cross-link to opnDossier_audit.md")

	// Stdout surfaced the generated-file listing.
	out := stdout.String()
	assert.Contains(t, out, "Generated CLI reference in "+outputDir,
		"command should announce output directory on stdout")
	assert.Contains(t, out, "Generated files:",
		"command should list generated files on stdout")
	assert.Contains(t, out, "opnDossier.md",
		"file listing should include the root page")
}

// TestDocsCmdIsHidden protects the UX decision to keep the docs command out of
// the default help output. If someone intentionally un-hides it, update this
// test and AGENTS.md together.
func TestDocsCmdIsHidden(t *testing.T) {
	assert.True(t, docsCmd.Hidden, "docs command must remain hidden — it is an authoring tool")
}
