package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

// defaultDocsOutputDir is the default output directory for Cobra-generated markdown docs.
// It is relative to the repo root so that `just generate-cli-docs` from any working
// directory produces a consistent location under docs/cli/.
const defaultDocsOutputDir = "docs/cli/"

// docsCmd generates markdown reference pages for every opnDossier command using
// Cobra's built-in doc.GenMarkdownTree. The command is hidden because it is an
// authoring tool, not an end-user feature — contributors invoke it via
// `just generate-cli-docs` to refresh the CLI reference shipped in the MkDocs site.
//
//nolint:gochecknoglobals // Cobra command
var docsCmd = &cobra.Command{
	Use:     "docs [output-directory]",
	Short:   "Generate markdown CLI reference",
	GroupID: "utility",
	Hidden:  true,
	Long: `Generate a markdown CLI reference for opnDossier and every subcommand.

If no output directory is given, the docs are written to ./docs/cli/ (relative
to the current working directory).

The generated markdown is intended to be included in the MkDocs site under
the "CLI Reference" navigation section. Re-run this command after changing
any Cobra Short/Long/Example text or flag wiring.`,
	Example: `  # Regenerate into the default docs/cli/ directory
  opnDossier docs

  # Regenerate into a custom directory
  opnDossier docs /tmp/opndossier-cli-docs/

  # Typical authoring workflow (from repo root)
  just generate-cli-docs`,
	Args: cobra.MaximumNArgs(1),
	RunE: runGenerateMarkdownDocs,
}

// runGenerateMarkdownDocs is the RunE handler for the hidden docs command.
// Extracted so it can be unit-tested without depending on the cobra.Command closure.
func runGenerateMarkdownDocs(cmd *cobra.Command, args []string) error {
	outputDir := defaultDocsOutputDir
	if len(args) > 0 {
		outputDir = args[0]
	}

	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("failed to create output directory %s: %w", outputDir, err)
	}

	// Identity linkHandler: Cobra's generated cross-link targets (e.g.,
	// "opnDossier_audit.md") already match the files written under docs/cli/,
	// so an identity mapping keeps the MkDocs site's internal links resolvable.
	// Stripping the "opnDossier_" prefix would break every cross-reference.
	linkHandler := func(name string) string { return name }

	// filePrepender injects an MkDocs-friendly front-matter banner so the page
	// reads as an auto-generated reference rather than human-authored prose.
	filePrepender := func(filename string) string {
		base := filepath.Base(filename)
		name := strings.TrimSuffix(base, filepath.Ext(base))
		title := strings.ReplaceAll(name, "_", " ")

		return fmt.Sprintf(`---
title: %s
generated: true
---

<!-- Auto-generated by 'opnDossier docs'. Do not edit by hand.
     Re-run 'just generate-cli-docs' to refresh after CLI changes. -->

`, title)
	}

	// Suppress Cobra's default "Auto generated by spf13/cobra on ..." footer.
	// Our filePrepender already banners these files as auto-generated, and
	// Cobra's footer uses inconsistent hyphenation ("Auto generated" vs.
	// "Auto-generated") across the tree. Silencing it keeps the site tidy.
	disableAutoGenTag(cmd.Root())

	// Generate the full command tree as markdown pages.
	if err := doc.GenMarkdownTreeCustom(cmd.Root(), outputDir, filePrepender, linkHandler); err != nil {
		return fmt.Errorf("failed to generate markdown docs: %w", err)
	}

	fmt.Fprintf(cmd.OutOrStdout(), "Generated CLI reference in %s\n", outputDir)

	// Surface the generated files so authors can spot-check the output.
	files, err := filepath.Glob(filepath.Join(outputDir, "*.md"))
	if err == nil && len(files) > 0 {
		fmt.Fprintln(cmd.OutOrStdout(), "Generated files:")
		for _, file := range files {
			fmt.Fprintf(cmd.OutOrStdout(), "  %s\n", file)
		}
	}

	return nil
}

// disableAutoGenTag walks the command tree rooted at c and sets
// DisableAutoGenTag on every command so Cobra's default footer is suppressed.
func disableAutoGenTag(c *cobra.Command) {
	c.DisableAutoGenTag = true
	for _, child := range c.Commands() {
		disableAutoGenTag(child)
	}
}

// init registers the hidden docs command with the root command.
func init() {
	rootCmd.AddCommand(docsCmd)
}
