name: CI Check

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  ci-check:
    name: ci-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true

      - name: Install Just
        uses: taiki-e/install-action@just

      - name: Install dependencies
        run: |
          go mod download
          go mod verify

      - name: Run CI Check
        run: just ci-check

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
