name: FOSSA License Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  fossa-scan:
    name: FOSSA License Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true
      
      - name: Download dependencies
        run: go mod download
      
      - name: Run FOSSA analysis
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          run-tests: true
          
      - name: Run FOSSA test (license policy check)
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          run-tests: true
        if: github.event_name == 'pull_request'

  generate-attribution:
    name: Generate License Attribution
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: fossa-scan
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true
      
      - name: Download dependencies  
        run: go mod download
        
      - name: Generate FOSSA attribution report
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          run-tests: false
          
      - name: Download attribution report
        run: |
          # Download the attribution report (this would be customized based on FOSSA API)
          echo "Attribution report would be generated here"
          # This is a placeholder - actual implementation depends on FOSSA setup
